# Curator Desk (R/Quarto) — GitHub Pages

project:
  type: website
  output-dir: docs
  execute-dir: project

execute:
  freeze: auto        #  avoids unnecessary re-renders in CI

website:
  title: "Curator Desk"
  navbar:
    left:
      - href: index.qmd
        text: Curator Desk
  page-navigation: true

format:
  html:
    theme: litera
    toc: false
    code-fold: false
    page-layout: full
    embed-resources: true
    minify: true
    css: styles.css
